services:
  - type: web
    name: discord-bot
    env: python
    buildCommand: ""
    startCommand: "python main.py"
    envVars:
      - key: DISCORD_TOKEN
        sync: true
      - key: HUGGINGFACE_TOKEN
        sync: true
